controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_products_index:
    path:       /api/products
    controller: App\Mytheresa\Presentation\Controller\GetProductsController
    methods:    GET