services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: my_password
      MYSQL_DATABASE: appdatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
  php:
    container_name: php
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ../app:/var/www/app
    depends_on:
      - db
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:8080'
    volumes:
      - ../app:/var/www/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db